# Generated by Django 4.1.5 on 2023-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='Is Superadmin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tksk',
            field=models.BooleanField(default=False, verbose_name='Is TKSK'),
        ),
    ]
