# Generated by Django 4.1.5 on 2023-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_admin_user_is_superadmin_user_is_tksk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Superadmin', 'superadmin'), ('Admin', 'admin'), ('TKSK', 'tksk')], default=2, max_length=20),
        ),
    ]
