# Generated by Django 4.1.6 on 2023-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cluster', models.CharField(max_length=100)),
                ('jumlah_k', models.IntegerField()),
                ('luas_bangunan', models.BooleanField(default=False)),
                ('luas_lahan', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('kulkas', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('pemanas_air', models.BooleanField(default=False)),
                ('telepon_rumah', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('perhiasan', models.BooleanField(default=False)),
                ('komputer', models.BooleanField(default=False)),
                ('sepeda', models.BooleanField(default=False)),
                ('motor', models.BooleanField(default=False)),
                ('mobil', models.BooleanField(default=False)),
                ('perahu', models.BooleanField(default=False)),
                ('motor_tempel', models.BooleanField(default=False)),
                ('perahu_motor', models.BooleanField(default=False)),
                ('kapal', models.BooleanField(default=False)),
                ('lahan', models.BooleanField(default=False)),
                ('sapi', models.BooleanField(default=False)),
                ('kerbau', models.BooleanField(default=False)),
                ('kuda', models.BooleanField(default=False)),
                ('babi', models.BooleanField(default=False)),
                ('kambing', models.BooleanField(default=False)),
                ('unggas', models.BooleanField(default=False)),
            ],
        ),
    ]
