# Generated by Django 4.1.6 on 2023-06-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenis',
            name='atribut',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
