# Generated by Django 4.1.6 on 2023-05-28 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0003_alter_rumah_koordinat_lat_alter_rumah_koordinat_long'),
        ('clustering', '0002_alter_jenis_ac_alter_jenis_babi_alter_jenis_gas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenis',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='babi',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='kambing',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='kapal',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='kerbau',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='komputer',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='kuda',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='kulkas',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='lahan',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='luas_bangunan',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='luas_lahan',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='mobil',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='motor_tempel',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='pemanas_air',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='perahu',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='perahu_motor',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='perhiasan',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='sapi',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='sepeda',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='telepon_rumah',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='jenis',
            name='unggas',
        ),
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas_bangunan', models.BooleanField(default=False, null=True)),
                ('luas_lahan', models.BooleanField(default=False, null=True)),
                ('gas', models.BooleanField(default=False, null=True)),
                ('kulkas', models.BooleanField(default=False, null=True)),
                ('ac', models.BooleanField(default=False, null=True)),
                ('pemanas_air', models.BooleanField(default=False, null=True)),
                ('telepon_rumah', models.BooleanField(default=False, null=True)),
                ('tv', models.BooleanField(default=False, null=True)),
                ('perhiasan', models.BooleanField(default=False, null=True)),
                ('komputer', models.BooleanField(default=False, null=True)),
                ('sepeda', models.BooleanField(default=False, null=True)),
                ('motor', models.BooleanField(default=False, null=True)),
                ('mobil', models.BooleanField(default=False, null=True)),
                ('perahu', models.BooleanField(default=False, null=True)),
                ('motor_tempel', models.BooleanField(default=False, null=True)),
                ('perahu_motor', models.BooleanField(default=False, null=True)),
                ('kapal', models.BooleanField(default=False, null=True)),
                ('lahan', models.BooleanField(default=False, null=True)),
                ('sapi', models.BooleanField(default=False, null=True)),
                ('kerbau', models.BooleanField(default=False, null=True)),
                ('kuda', models.BooleanField(default=False, null=True)),
                ('babi', models.BooleanField(default=False, null=True)),
                ('kambing', models.BooleanField(default=False, null=True)),
                ('unggas', models.BooleanField(default=False, null=True)),
                ('IDJTG', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtks.rumah')),
            ],
        ),
    ]
