<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-07-14 17:52
=======
# Generated by Django 4.1.6 on 2023-07-14 17:25
>>>>>>> 961d98c5e0cd14f35c069bfaebbce432563db7a1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='nilai',
<<<<<<< HEAD
            field=models.FloatField(blank=True, default='0', null=True),
=======
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
>>>>>>> 961d98c5e0cd14f35c069bfaebbce432563db7a1
        ),
    ]
