# Generated by Django 4.1.6 on 2023-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='nilai',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
