# Generated by Django 4.1.5 on 2023-06-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0003_alter_rumah_koordinat_lat_alter_rumah_koordinat_long'),
        ('penerima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Belum Diverifikasi', 'Belum Diverifikasi'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Balum Diverifikasi', max_length=20)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtks.anggota')),
            ],
        ),
    ]
