# Generated by Django 4.1.5 on 2023-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='nilai',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
