# Generated by Django 4.1.5 on 2023-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0002_ranking_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerima',
            name='foto_bukti',
            field=models.FileField(null=True, upload_to='bukti/'),
        ),
    ]
