# Generated by Django 4.1.6 on 2023-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0002_ranking_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='nilai',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
