# Generated by Django 4.1.5 on 2023-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0002_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='status',
            field=models.CharField(choices=[('Belum Diverifikasi', 'Belum Diverifikasi'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Penerima', 'Penerima')], default='Balum Diverifikasi', max_length=20),
        ),
    ]
