# Generated by Django 4.1.5 on 2023-07-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0001_initial'),
        ('penerima', '0003_alter_penerima_foto_bukti'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='bansos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dtks.bansos'),
        ),
    ]
