# Generated by Django 4.1.5 on 2023-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penerima', '0004_ranking_bansos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='status',
            field=models.CharField(choices=[('Belum Diverifikasi', 'Belum Diverifikasi'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Penerima', 'Penerima')], default='Belum Diverifikasi', max_length=20),
        ),
    ]
