# Generated by Django 4.1.5 on 2023-04-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penerima',
        ),
    ]
