# Generated by Django 4.1.5 on 2023-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='IDJTG_ART',
            field=models.CharField(max_length=20),
        ),
    ]
