# Generated by Django 4.1.6 on 2023-07-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='gas',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
