# Generated by Django 4.1.5 on 2023-05-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='koordinat_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='koordinat_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
