# Generated by Django 4.1.5 on 2023-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0002_alter_rumah_koordinat_lat_alter_rumah_koordinat_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='koordinat_lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='koordinat_long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
