# Generated by Django 4.1.6 on 2023-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0003_alter_aset_ac_alter_aset_gas_alter_aset_kapal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='ac',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='gas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='kapal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='komputer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='kulkas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='lahan',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='mobil',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='motor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='motor_tempel',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='pemanas_air',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='perahu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='perahu_motor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='perhiasan',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='rumah_lain',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='sepeda',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='telepon_rumah',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='tv',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
