# Generated by Django 4.1.6 on 2023-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0004_alter_aset_ac_alter_aset_gas_alter_aset_kapal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='tgl_kehamilan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
