# Generated by Django 4.1.6 on 2023-07-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0005_alter_anggota_tgl_kehamilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumah',
            name='jum_anggota',
            field=models.IntegerField(default=0),
        ),
    ]
