# Generated by Django 4.1.5 on 2023-08-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0006_rumah_jum_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='IDJTG_ART',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nik',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='IDJTG',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
