# Generated by Django 4.1.6 on 2023-07-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtks', '0006_rumah_jum_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='IDJTG',
            field=models.CharField(max_length=255),
        ),
    ]
