# Generated by Django 4.1.5 on 2023-04-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penerima',
        ),
    ]
